model:
  base_momentum: 0.99
  backbone:
    type: "resnet50"
    pretrained: true
  projection:
    type: "MLP"
    input_dim: 2048
    hidden_dim: 4096
    output_dim: 256
  predictor:
    type: "MLP"
    input_dim: 256
    hidden_dim: 4096
    output_dim: 256

amp:
  sync_bn: True
  opt_level: "O1"

data:
  resize_size: 224
  data_workers: 32
  train_batch_size: 64
  val_batch_size: 64
  dual_views: true
  num_examples: 270000

  dset_path: "/dhc/dsets/CAMELYON/CAMELYON16/"
  coords_path: "/dhc/home/benjamin.bergner/netstore-old/projects/IPS/datasets/camelyon/data/coords_train.pkl"
  level: 0
  tile_size: 256

optimizer:
  type: lars
  base_lr: 0.2
  momentum: 0.9
  weight_decay: 1.5e-6
  total_epochs: 1000
  warmup_epochs: 10
  exclude_bias_and_bn: true

checkpoint:
  resume_path:
  save_epoch: 10
  ckpt_path: "/dhc/home/benjamin.bergner/netstore-old/projects/gigapixel/giganet/models/camelyon16/byol_repr/{}_{}.pth.tar"

log:
  log_step: 50
  log_dir:

stage: "train"
distributed: true